pygments:         true
permalink:        pretty
markdown:         rdiscount
rdiscount:
  extensions:     [smart]

# ---------
# Kickstarter specific settings
#
# Basics
#
# 0. Page title and theme
title:            Stair-Rover
theme:            basic
#
# 1. Your website ( could be same as this page - see below )
website:          http://www.electroninks.com
#
# 2. URL of this page
url:              http://electroninks.github.io/
#
# 3. About your kickstarter project
project:
  #
  # Name of the project
  name:           Circuit Scribe
  #
  # URL of the project. Use short urls to ensure you track the visits (Optional)
  url:            http://www.kickstarter.com/projects/electroninks/1444409174?token=356898ca
  #
  # URL of a cover photo of your project
  cover_image:    http://s15.postimg.org/4a1rhk2uj/CS_KS_COVER_03.jpg
  #
  # Use a one-liner to describe your project
  description:    Circuit Scribe is a rollerball pen with conductive silver ink. It makes building circuits as easy as doodling.
#
# 4. Your Twitter handle
twitter_handle:   Electroninks
#
# 5. Your Google analytics ID (Optional)
google_analytics: 
#
# 6. Welcome text, add <br /> to break lines
welcome_text:     |
  Circuit Scribe is live on KICKSTARTER! <br />
  We can't wait to get Circuit Scribe into your hands and see what you MAKE!   <br />
  But we need your help to make it happen! <br /> Please pick up a pen & a kit, and most importantly,
  SHARE with your friends!  <br /> Thank you! - The Electroninks Team
